services:
  db:
    image: postgres:15
    container_name: postgres_dev
    environment:
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: nom_de_la_base
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  pgdata:
